server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create # none, create-drop, create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

logging:
  level:
    root: INFO
    com.daniel.stocknotifier.services.StocksService: INFO
  file:
    name: logs/myapplication.log
    max-size: 10MB
    max-histroy: 10
